# Site settings
title:          M1 | Michał Kozłowski
description:    "My personnal blog"

# Google Analytics
google_analytics: none

# Author
author:
  name:         Michał Kozłowski    
  site:         https://m1chol.github.io/m1/
  email:        m1chol@proton.me@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
